[package]
name = "object-alloc-test"
version = "0.1.0"
authors = ["Joshua Liebow-Feeser <hello@joshlf.com>"]

[dependencies]
interpolate_idents = "0.1"
lazy_static = "0.2"
libc = "0.2"
object-alloc = { path = "../object-alloc" }
quickcheck = "0.4"
rand = "0.3"
sysconf = { path = "../sysconf" }
twox-hash = "1.1"
winapi = "0.2"
