[package]
name = "elfmalloc"
version = "0.1.0"
authors = ["Eli Rosenthal <ezrosenthal@gmail.com>", "Joshua Liebow-Feeser <hello@joshlf.com>"]

[features]
prime_schedules = ["bagpipe/prime_schedules"]
huge_segments = ["bagpipe/huge_segments"]
no_lazy_region = []
nightly = []

[dependencies]
bagpipe = { path = "../bagpipe" }
bsalloc = { path = "../bsalloc" }
lazy_static = "0.2"
mmap-alloc = { path = "../mmap-alloc" }
num_cpus = "1.5"
