[package]
name = "malloc-bind"
version = "0.1.0"
authors = ["Joshua Liebow-Feeser <hello@joshlf.com>"]

[dependencies]
errno = "0.2"
lazy_static = "0.2"
libc = "0.2"
sysconf = { path = "../sysconf" }
