[package]
name = "bsalloc"
version = "0.1.0"
authors = ["Eli Rosenthal <ezrosenthal@gmail.com>"]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
lazy_static = { version = "0.2", features = ["spin_no_std"] }
mmap-alloc = { path = "../mmap-alloc" }
